# Generated by Django 5.2.7 on 2025-11-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_importeddatarecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportprocess',
            name='table_name',
            field=models.CharField(help_text='Nome da tabela criada no banco de dados', max_length=255, unique=True, verbose_name='Nome da Tabela'),
        ),
    ]
